import CheckOutFormModel from "./CheckOutFormModel";
const {
  formField: {
    Nom,
    Prenom,
    numSs,
    numCni,
    prenomAr,
    nomAr,
    sexe,
    dateNaiss,
    situationFamiliale,
    Enfant,
    nbrEnfant,
    nomEps,
    prenomEps,
    nomMere,
    prenomMere,
    prenomPere,
    prenomEpsAr,
    nomEpsAr,
    ccp,
    rib,
    adresse,
    mobile,
    email,
    droitCong,
    managId,
    idP,
    Role,
    password,
    RépéterLeMotDePasse,
  },
} = CheckOutFormModel;

const Data = {
  [Nom.name]: "",
  [Prenom.name]: "",
  [numSs.name]: "",
  [numCni.name]: "",
  [prenomAr.name]: "",
  [nomAr.name]: "",
  [sexe.name]: "",
  [dateNaiss.name]: "",
  [situationFamiliale.name]: "",
  [nomEps.name]: "",
  [prenomEps.name]: "",
  [Enfant.name]: "",
  [nbrEnfant.name]: "",
  [nomMere.name]: "",
  [prenomMere.name]: "",
  [prenomPere.name]: "",
  [prenomEpsAr.name]: "",
  [nomEpsAr.name]: "",
  [ccp.name]: "",
  [rib.name]: "",
  [adresse.name]: "",
  [droitCong.name]: "",
  [idP.name]: "",

  [mobile.name]: "",
  [email.name]: "",
  [managId.name]: "",
  [Role.name]: "",
  [password.name]: "",
  [RépéterLeMotDePasse.name]: "",
};
export default Data;
